src/BearcatExpress/Controllers/OffersController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using BearcatExpress.Models;

namespace BearcatExpress.Controllers
{
    public class OffersController : Controller
    {
        private ApplicationDbContext _context;

        public OffersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Offers
        public IActionResult Index()
        {
            return View(_context.Offer.ToList());
        }

        // GET: Offers/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Offer offer = _context.Offer.Single(m => m.OfferID == id);
            if (offer == null)
            {
                return HttpNotFound();
            }

            return View(offer);
        }

        // GET: Offers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Offers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Offer.Add(offer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: Offers/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Offer offer = _context.Offer.Single(m => m.OfferID == id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: Offers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Offer offer)
        {
            if (ModelState.IsValid)
            {
                _context.Update(offer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: Offers/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Offer offer = _context.Offer.Single(m => m.OfferID == id);
            if (offer == null)
            {
                return HttpNotFound();
            }

            return View(offer);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Offer offer = _context.Offer.Single(m => m.OfferID == id);
            _context.Offer.Remove(offer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/BearcatExpress/Controllers/ShippingAddressesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using BearcatExpress.Models;

namespace BearcatExpress.Controllers
{
    public class ShippingAddressesController : Controller
    {
        private ApplicationDbContext _context;

        public ShippingAddressesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: ShippingAddresses
        public IActionResult Index()
        {
            return View(_context.ShippingAddress.ToList());
        }

        // GET: ShippingAddresses/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ShippingAddress shippingAddress = _context.ShippingAddress.Single(m => m.AddressId == id);
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }

            return View(shippingAddress);
        }

        // GET: ShippingAddresses/Create
        public IActionResult Create()
        {
            if(User.Identity.IsAuthenticated)
            {
                return View("Create");
            }
            else
            {
                return View("ShippingWithoutLogin");
            }
          
        }

        // POST: ShippingAddresses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ShippingAddress shippingAddress)
        {
            if (ModelState.IsValid)
            {
                _context.ShippingAddress.Add(shippingAddress);
                _context.SaveChanges();
                return RedirectToAction("ShipmentDetails");
            }
            return View(shippingAddress);
        }

        // GET: ShippingAddresses/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ShippingAddress shippingAddress = _context.ShippingAddress.Single(m => m.AddressId == id);
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }
            return View(shippingAddress);
        }

        // POST: ShippingAddresses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ShippingAddress shippingAddress)
        {
            if (ModelState.IsValid)
            {
                _context.Update(shippingAddress);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shippingAddress);
        }

        // GET: ShippingAddresses/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ShippingAddress shippingAddress = _context.ShippingAddress.Single(m => m.AddressId == id);
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }

            return View(shippingAddress);
        }

        // POST: ShippingAddresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            ShippingAddress shippingAddress = _context.ShippingAddress.Single(m => m.AddressId == id);
            _context.ShippingAddress.Remove(shippingAddress);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult ShipmentDetails()
        {
            return View();
        }

        public IActionResult Payment()
        {
            return View();
        }
        public IActionResult Confirmation()
        {
            return View();
        }
    }
}

src/BearcatExpress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="~/css/site.css" />*@
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sre-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    @using System.Security.Claims
    <div style="background-image:url('/images/new.jpg');height: 75px; width: 100%;padding-top:10px">
     
         <h2 style="color:black;font-family:Corbel;padding:0px 115px 10px">Bearcat Express</h2>
     </div>

    <div style="background-color:lightsalmon;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;padding-left:105px;" class="nav nav-stacked">
        
        <ul class="nav navbar-nav">
            <li><a style="color:black;font-size:medium" asp-controller="Home" asp-action="Index">Home</a></li>
            <li><a style="color:black;font-size:medium" asp-controller="ShippingAddresses" asp-action="Create">Shipping</a></li>
            <li><a style="color:black;font-size:medium" asp-controller="Home" asp-action="Track">Track</a></li>
            <li><a style="color:black;font-size:medium" asp-controller="Home" asp-action="AboutUs">About</a></li>
            @if (User.IsSignedIn() && User.IsInRole("Admin"))
            {
                <li><a style="color:black;font-size:medium" asp-controller="Offers" asp-action="Create">Admin</a></li>
            }
        </ul>
        
        @await Html.PartialAsync("_LoginPartial")
    </div>
   

    <div class="container body-content" >
        @RenderBody()
    </div>
  
    <div style="padding-top:5%;">
        <hr />
        <div class="row" style="padding-left:30px;">
            <div class="col-sm-2">
                <p>Email:<a href="mailto:s525078@mail.nwmissouri.edu?Subject=Feedback" target="_blank"><img src="~/images/Message Squared-48.png"></a></p>
                <a asp-controller="Home" asp-action="FAQs"><p>FAQs</p></a>
            </div>
            <div class="col-sm-2 pull-right">
                Follow Us:
                <a href="https://www.facebook.com/ashish.pandey91" target="_blank"><img src="~/images/Facebook-48.png"></a>
                <a href="https://twitter.com/Ashish_Pandey91" target="_blank"><img src="~/images/Twitter-48.png"></a>
            </div>
        </div>
        <div class="row">
            <p style="text-align:center">&copy; 2016 - BearcatExpress</p>
        </div>
    </div>
    

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>